spring.application.name=iot-platform-registry

management.endpoints.web.exposure.include=refresh

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=ALWAYS
spring.jpa.show-sql=true

iot.crearts.registry.message=default hello