name: docker-iot-platform
services:
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    restart: unless-stopped
    ports:
      - '15672:15672'
      - '1883:1883'
      - '5672:5672'
    env_file:
      - rabbitmq/config/login.env
    volumes:
      - type: bind
        source: ./rabbitmq/config/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
        read_only: true
      - type: bind
        source: ./rabbitmq/config/definitions.json
        target: /etc/rabbitmq/definitions.json
        read_only: true
      - type: bind
        source: ./rabbitmq/config/enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
        read_only: true

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot-platform-registry

  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-otlp-receiver"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: "grafana/grafana:11.1.0"
    ports:
      - "3000:3000"
    volumes:
      - "../tmp/build/grafana:/var/lib/grafana:cached"